version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: youtube-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: youtube_trending
      MONGO_URI: mongodb://mongodb:27017/
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - youtube-network

  # MongoDB Express (Web UI)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: youtube-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - youtube-network

  # Spark Master
  spark-master:
    image: bitnami/spark:3.5
    container_name: youtube-spark-master
    environment:
      - SPARK_MODE=master
      - MONGO_URI=mongodb://mongodb:27017/
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ../spark:/opt/bitnami/spark/jobs
      - ../data:/opt/bitnami/spark/data
    networks:
      - youtube-network

  # Spark Worker
  spark-worker:
    image: bitnami/spark:3.5
    container_name: youtube-spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - MONGO_URI=mongodb://mongodb:27017/
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    volumes:
      - ../spark:/opt/bitnami/spark/jobs
      - ../data:/opt/bitnami/spark/data
    networks:
      - youtube-network

volumes:
  mongodb_data:

networks:
  youtube-network:
    driver: bridge
